/*CHECK CALENDER OF IQVIA*/

PROC FREQ DATA=redivis_export;
TABLES MONTH_YEAR_CODE;
RUN;


/*YEAR*/
PROC SQL;
   CREATE TABLE CAL_YEAR AS 
   SELECT DISTINCT 
		  INPUT(substr(CAT(T1.MONTH_YEAR_CODE),1,4),4.) AS YEAR
      FROM WORK.redivis_export t1
      GROUP BY CALCULATED YEAR
	  ORDER BY CALCULATED YEAR;
QUIT;

/*QUARTER*/
PROC SQL;
   CREATE TABLE CAL_QTR_0 AS 
   SELECT DISTINCT 
   		  INPUT(substr(CAT(T1.MONTH_YEAR_CODE),1,4),4.) AS YEAR,
		  input(SUBSTR(CAT(T1.MONTH_YEAR_CODE),5,2),2.) AS MONTH,
		  CASE WHEN input(SUBSTR(CAT(T1.MONTH_YEAR_CODE),5,2),2.) IN (1,2,3) THEN 1
			   WHEN input(SUBSTR(CAT(T1.MONTH_YEAR_CODE),5,2),2.) IN (4,5,6) THEN 2
			   WHEN input(SUBSTR(CAT(T1.MONTH_YEAR_CODE),5,2),2.) IN (7,8,9) THEN 3
			   WHEN input(SUBSTR(CAT(T1.MONTH_YEAR_CODE),5,2),2.) IN (10,11,12) THEN 4 
		       ELSE 9999999 END AS QUARTER
      FROM WORK.redivis_export t1
      GROUP BY CALCULATED YEAR,
			   CALCULATED QUARTER
      ORDER BY CALCULATED YEAR,
			   CALCULATED QUARTER;
QUIT;

/**********************************************DELETE QUARTER IF IT'S NOT REACH TO CORRECT MONTH******************************/
DATA CAL_QTR_1;
SET CAL_QTR_0;
BY YEAR QUARTER;

/*********************************REMEMBER TO CHANGE THE YEAR HERE************************************************************************************/
IF YEAR=2020 THEN DO;
	IF LAST.MONTH/3<last.quarter then delete;
END;
run;

PROC SQL;
   CREATE TABLE CAL_QTR AS 
   SELECT DISTINCT 
		 YEAR,
		 QUARTER
		FROM WORK.CAL_QTR_1 t1
;
QUIT;


/*MONTH*/
PROC SQL;
   CREATE TABLE CAL_MONTH AS 
   SELECT DISTINCT 
   		  INPUT(substr(CAT(T1.MONTH_YEAR_CODE),1,4),4.) AS YEAR,
	      input(SUBSTR(CAT(T1.MONTH_YEAR_CODE),5,2),2.) AS MONTH
      FROM WORK.redivis_export t1
      GROUP BY CALCULATED YEAR,
			   CALCULATED MONTH
	  ORDER BY CALCULATED YEAR,
			   CALCULATED MONTH
;
QUIT;

DATA CAL_0;
SET CAL_YEAR CAL_QTR CAL_MONTH;
RUN;

PROC SORT DATA=CAL_0;
BY YEAR MONTH;
RUN;

DATA CAL_1;
SET CAL_0;
BY YEAR MONTH;
	IF YEAR=YEAR(TODAY()) THEN DO;
/*DELETE YEAR IF MONTH NOT REACH TO 12*/
		IF LAST.MONTH<12 THEN DO;
			IF QUARTER=. AND MONTH=. THEN DELETE;
			END;
	END;
RUN;