Data redivis_export_0;
set redivis_export;
/*If COUNTY_TERRITORY in ('ERIE','MONROE','SUFFOLK') then delete;*/
RUN;

Data redivis_export_1;
set redivis_export_0;
if COUNTY_TERRITORY eq 'ROCHESTER_NY' then COUNTY_TERRITORY='ROCHESTER';
if COUNTY_TERRITORY eq 'BUFFALO_NY' then COUNTY_TERRITORY='BUFFALO';
if COUNTY_TERRITORY eq 'BROOKHAVEN TOWNSHIP_NY' then COUNTY_TERRITORY='BROOKHAVEN';

run;

PROC FREQ DATA=REDIVIS_EXPORT;
TABLES COUNTY_TERRITORY;
RUN;

PROC FREQ DATA=REDIVIS_EXPORT_1;
TABLES COUNTY_TERRITORY;
RUN;