/*YEAR*/
PROC SQL;
   CREATE TABLE IQVIA_Y AS 
   SELECT DISTINCT 
		  t1.ReporterId,
		  T1.YEAR,
          /* SUM_of_PROJECTED_TRX */
            (SUM(t1.PROJECTED_TRX)) FORMAT=BEST32. AS SUM_of_PROJECTED_TRX
      FROM WORK.IQVIA_0 t1
      GROUP BY t1.ReporterId,
               t1.YEAR;
QUIT;

/*QUARTER*/
PROC SQL;
   CREATE TABLE IQVIA_Q AS 
   SELECT DISTINCT 
		  t1.ReporterId,
		  T1.YEAR, 
		  T1.QUARTER,
          /* SUM_of_PROJECTED_TRX */
            (SUM(t1.PROJECTED_TRX)) FORMAT=BEST32. AS SUM_of_PROJECTED_TRX
      FROM WORK.IQVIA_0 t1
      GROUP BY t1.ReporterId,
	  		   T1.YEAR,
               t1.QUARTER;
QUIT;

/*MONTH*/
PROC SQL;
   CREATE TABLE WORK.IQVIA_M AS 
   SELECT DISTINCT 
		  t1.ReporterId,
		  T1.YEAR, 
		  T1.MONTH,
          /* SUM_of_PROJECTED_TRX */
            (SUM(t1.PROJECTED_TRX)) FORMAT=BEST32. AS SUM_of_PROJECTED_TRX
      FROM WORK.IQVIA_0 t1
      GROUP BY t1.ReporterId,
	  	       T1.YEAR,
               t1.MONTH;
QUIT;

DATA IQVIA_2;
SET IQVIA_Y IQVIA_Q IQVIA_M;
RUN;

PROC SQL;
   CREATE TABLE WORK.IQVIA_3 AS 
   SELECT DISTINCT 
		  t1.ReporterId,
		  '2.14.2' AS MEASUREID,
		  T1.SUM_of_PROJECTED_TRX AS NUMERATOR,
		  T2.POP AS DENOMINATOR,
/*		  T1.COUNTY_TERRITORY,*/
/*		  T2.LOCATION,*/
		  T1.MONTH,
		  T1.QUARTER,
		  T1.YEAR,
		  CASE WHEN T1.SUM_of_PROJECTED_TRX EQ . THEN 1
		       ELSE 0 END AS IsSuppressed,
		  "This data is from IQVIA DATASET_&IQVIA_VERSION." AS NOTES,
		  '' AS STRATIFICATION
      FROM WORK.IQVIA_2 t1 LEFT JOIN POPEST T2 ON t1.REPORTERID=T2.REPORTERID AND T1.YEAR=T2.YEAR
      ORDER BY t1.ReporterId,
	  	       T1.YEAR,
			   T1.QUARTER,
               t1.MONTH;
QUIT;

PROC FREQ DATA=IQVIA_3; 	
TABLE REPORTERID;
RUN;

PROC FREQ DATA=dan.NY_IQVIA_APR20;
TABLES REPORTERID;
RUN;